package com.example.mementoandroid.ui.album

import android.net.Uri
import com.example.mementoandroid.util.formatBackendDateTime
import org.json.JSONObject

/** Shown when an album has no user-chosen title and the first photo has no place label / GPS. */
const val UNTITLED_ALBUM_DISPLAY = "Untitled album"

private val COORDINATE_STYLE_ALBUM_TITLE =
    Regex("""^\d+\.\d+°\s+[NS],\s+\d+\.\d+°\s+[EW]$""")

data class AlbumPhotoUi(
    val id: String,
    val imageRes: Int? = null,
    val uri: Uri? = null,
    val imageUrl: String? = null,
    val audioUrl: String? = null,
    val caption: String? = null,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val locationName: String? = null,
    val dateAdded: String? = null,
    val takenAt: String? = null,
    val userId: Int? = null,
    /** Grid/map skeleton tiles when no real image row is loaded yet. */
    val isPlaceholder: Boolean = false,
) {
    init {
        if (!isPlaceholder) {
            require(listOf(imageRes, uri, imageUrl).any { it != null }) {
                "One of imageRes, uri, or imageUrl must be set"
            }
        }
    }

    companion object {
        /** Matches a 3-column grid with a few rows so the album view never starts empty. */
        const val DEFAULT_GRID_SKELETON_COUNT = 12

        fun gridSkeleton(index: Int) = AlbumPhotoUi(
            id = "skeleton-$index",
            isPlaceholder = true,
        )

        fun defaultGridSkeletons(): List<AlbumPhotoUi> =
            (0 until DEFAULT_GRID_SKELETON_COUNT).map { gridSkeleton(it) }
    }
}

data class AlbumUi(
    val id: Int,
    val name: String,
    val ownerId: Int? = null,
    val coverImageUrls: List<String> = emptyList(),
    /** Oldest image in the album (`date_added`); matches backend cover order. */
    val firstImageLocationName: String? = null,
    val firstImageTakenAt: String? = null,
    val firstImageDateAdded: String? = null,
)

private fun formatHomeFallbackTimestamp(takenAt: String?, dateAdded: String?): String? {
    val raw = takenAt?.trim()?.takeIf { it.isNotEmpty() }
        ?: dateAdded?.trim()?.takeIf { it.isNotEmpty() }
    return formatBackendDateTime(raw) ?: raw
}

/** Title for home grid/list: user-chosen names stay as-is; auto/placeholder names use first photo place. */
fun AlbumUi.titleForHome(): String {
    val fromFirst = firstImageLocationName?.trim()?.takeIf { it.isNotEmpty() }
    if (!name.isAutoGeneratedAlbumTitle()) return name
    if (fromFirst != null) return fromFirst
    return formatHomeFallbackTimestamp(firstImageTakenAt, firstImageDateAdded)
        ?: UNTITLED_ALBUM_DISPLAY
}

private fun String.isAutoGeneratedAlbumTitle(): Boolean {
    val t = trim()
    if (t.isEmpty()) return true
    if (t.equals(UNTITLED_ALBUM_DISPLAY, ignoreCase = true)) return true
    return t.matches(COORDINATE_STYLE_ALBUM_TITLE)
}

/** Home "My Photos" row label: place name, else formatted photo/upload time, else untitled. */
fun AlbumPhotoUi.standaloneMementoTitle(): String {
    val place = locationName?.trim()?.takeIf { it.isNotEmpty() }
    if (place != null) return place
    return formatHomeFallbackTimestamp(takenAt, dateAdded) ?: UNTITLED_ALBUM_DISPLAY
}

fun JSONObject.parseAlbumUi(): AlbumUi {
    val coverUrls = if (has("cover_image_urls")) {
        val a = getJSONArray("cover_image_urls")
        (0 until a.length()).map { j -> a.getString(j) }
    } else emptyList()
    return AlbumUi(
        id = getInt("id"),
        name = getString("name"),
        ownerId = if (has("owner_id")) getInt("owner_id") else null,
        coverImageUrls = coverUrls,
        firstImageLocationName = optString("first_image_location_name", "").takeIf { it.isNotBlank() },
        firstImageTakenAt = optString("first_image_taken_at", "").takeIf { it.isNotBlank() },
        firstImageDateAdded = optString("first_image_date_added", "").takeIf { it.isNotBlank() },
    )
}

data class FriendUi(
    val id: String,
    val username: String,
    val profilePictureUrl: String? = null
)

enum class AddPhotoSource {Camera, Photos}

/** How album photos are sorted or filtered in the grid and feed. */
enum class AlbumSortKind {
    TIME_NEWEST_FIRST,
    TIME_OLDEST_FIRST,
    BY_LOCATION,
    UPLOADED_BY
}

/** Applied sort/filter: kind + optional user id for UPLOADED_BY. */
data class AlbumSort(
    val kind: AlbumSortKind,
    val uploadedByUserId: Int? = null
)

fun List<AlbumPhotoUi>.sortedAndFiltered(sort: AlbumSort): List<AlbumPhotoUi> {
    val (placeholders, nonPlaceholders) = partition { it.isPlaceholder }
    var list = nonPlaceholders
    if (sort.kind == AlbumSortKind.UPLOADED_BY && sort.uploadedByUserId != null) {
        list = list.filter { it.userId == sort.uploadedByUserId }
    }
    val sorted = when (sort.kind) {
        AlbumSortKind.TIME_NEWEST_FIRST -> list.sortedByDescending { it.takenAt ?: it.dateAdded ?: "" }
        AlbumSortKind.TIME_OLDEST_FIRST -> list.sortedBy { it.takenAt ?: it.dateAdded ?: "" }
        AlbumSortKind.BY_LOCATION -> {
            list.groupBy { p ->
                when {
                    p.latitude != null && p.longitude != null -> "%.4f,%.4f".format(p.latitude, p.longitude)
                    else -> "_no_location"
                }
            }.toSortedMap().values.flatten()
        }
        AlbumSortKind.UPLOADED_BY -> list.sortedByDescending { it.takenAt ?: it.dateAdded ?: "" }
    }
    return sorted + placeholders.sortedBy { it.id }
}

/** Default state for the album grid when no album is open or images are not loaded yet. */
fun MutableList<AlbumPhotoUi>.replaceWithAlbumGridSkeletons() {
    clear()
    addAll(AlbumPhotoUi.defaultGridSkeletons())
}